// GLSL parser generated by pegjs - https://www.pegjs.org
/*#include ../peglsl/glsl.js*/

self.onmessage = function (m) {
    "use strict";

    var glsl_code = m.data,
        
        glsl_o;
    
    glsl_o = _PEGLSL.parse(glsl_code);
    
    postMessage(glsl_o);
};
