/*
    Client global configuration file
    
    This file is generated by a production system and filled with the correct settings (aka. domain where fss/fsdb is and the protocol used)
*/

var _ws_protocol = "ws",
    _domain = "127.0.0.1";